projects:
  - name: "frontend"
    actions: ["s3:PutObject",
              "s3:GetObject",
              "s3:DeleteObject",
              "s3:ListBucket"
              ]
    resources: ["*"]
    repo_name: "frontend"
    branch_or_ref: "master"
    build_spec: "buildspec.yml"
  - name: "backend"
    actions: ["ecr:GetAuthorizationToken",
                    "ecr:BatchGetImage",
                    "ecr:BatchCheckLayerAvailability",
                    "ecr:InitiateLayerUpload",
                    "ecr:UploadLayerPart",
                    "ecr:CompleteLayerUpload",
                    "ecr:PutImage",
                    "s3:GetObject",
                    "s3:GetObjectVersion",
                    "s3:PutObject",
                    "s3:ListBucket"
              ]
    resources: ["*"]
    repo_name: "backend"
    branch_or_ref: "master"
    build_spec: "buildspec.yml"